# Generated by Django 5.0.6 on 2024-07-05 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebClick', '0002_rename_email_usuario_correo_remove_usuario_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Templates_Products',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=25)),
                ('precio', models.IntegerField()),
                ('imagen_url', models.CharField(max_length=300)),
                ('descripcion', models.CharField(max_length=70)),
                ('descuento', models.IntegerField()),
            ],
        ),
    ]
