# Generated by Django 5.0.6 on 2024-07-05 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebClick', '0003_templates_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates_Products',
            new_name='Templates_Product',
        ),
    ]
